{{- $currentScope := .}}
{{- $cpath := .Values.configs.path }}
{{- range $path, $_ :=  .Files.Glob  $cpath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path | trimSuffix ".yaml" }}-configmap
data:
  {{- with $currentScope}}
    {{ base $path }}: |
    {{- ( .Files.Get $path ) | nindent 8 }}
    {{- end }}
---
{{- end }}
---
{{- $ecurrentScope := .}}
{{- $epath := .Values.env.path }}
{{- range $path, $_ :=  .Files.Glob  $epath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path | trimSuffix ".yaml" }}-configmap
data:
  {{- with $ecurrentScope}}
    {{- ( .Files.Get $path ) | nindent 2 }}
  {{- end }}
---
{{- end }}
---
{{- $jcurrentScope := .}}
{{- $jpath := .Values.json.path }}
{{- range $path, $_ :=  .Files.Glob  $jpath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path | trimSuffix ".json" }}-configmap
data:
  {{- with $jcurrentScope}}
    {{ base $path }}: |
    {{- ( .Files.Get $path ) | nindent 8 }}
    {{- end }}
---
{{- end }}